[workspace]
authors = ["Uspfe <benjamin.bogenberger@tum.de>"]
channels = ["conda-forge"]
name = "issac_sim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"

[system-requirements]
libc="2.35"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://pypi.nvidia.com"]

[pypi-dependencies]
isaacsim = { version = "==5.1.0", extras = ["all", "extscache", "ros2"] }

